scrape_configs:
  - job_name: 'otel-collector'

    scrape_interval: 1s

    static_configs:
      - targets: ['otel_integration_testing:10000']
        labels:
          group: 'integration_tesitng'

      - targets: ['otel_performance_testing:10001']
        labels:
          group: 'performance_testing'

      - targets: ['otel_adhoc_testing:10002']
        labels:
          group: 'adhoc_testing'

      - targets: ['otel:8888']
        labels:
          group: 'otel-collector-itself'
