scrape_configs:
  - job_name: 'otel-collector'

    scrape_interval: 1s

    static_configs:
      - targets: ['otel:10000']
        labels:
          group: 'production'

      - targets: ['otel:8888']
        labels:
          group: 'otel-collector-itself'
