scrape_configs:
  - job_name: 'otel-collector'

    scrape_interval: 1s

    static_configs:
      - targets: ['otel_integration_testing:10000']
        labels:
          group: 'integration_testing'

      - targets: ['otel_performance_testing:10002']
        labels:
          group: 'performance_testing'

      - targets: ['otel_adhoc_testing:10004']
        labels:
          group: 'adhoc_testing'

      - targets: ['otel_performance_testing:10005']
        labels:
          group: 'otel-collector-itself-performance'

      - targets: ['otel_integration_testing:10006']
        labels:
          group: 'otel-collector-itself-integration'

      - targets: ['otel_adhoc_testing:10007']
        labels:
          group: 'otel-collector-itself-adhoc'
